name: MWE

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: mongo:4.0.12
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo 'mongodb://admin:password@localhost:27017/test?authSource=admin&replicaSet=rs0'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: mongo localhost:${{ job.services.database.ports['27017']  }}/test?authSource=admin&replicaSet=rs0


