name: MWE

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: mongo:4.0.12
        ports:
          - 27017/tcp
    steps:
      - uses: actions/checkout@v2
      - name: Start the database
        run: mongod --port 27017 --replSet "rs0" --dbpath . --fork --syslog
      - name: Initialize the replica set
        run: |
            set -e

            mongo <<EOF
                rs.initiate({
                    _id : "rs0",
                    members: [
                        { _id: 0, host: "localhost:27017" }
                    ]
                });

                while (rs.status().myState !== 1) {
                    print('sleeping...');
                    sleep(200);
                }

                exit
            EOF
      - name: Create user
        run: |
            set -e

            mongo <<EOF
                var adminDB = 'admin';
                var username = 'admin';
                var password = 'password';

                db = db.getSiblingDB(adminDB);
                db.dropAllUsers();
                db.createUser({
                  user: username,
                  pwd: password,
                  roles: [ { role: 'root', db: adminDB, } ],
                });

                exit
            EOF
      - name: Test the database
        run: mongo mongodb://admin:password@localhost:${{ job.services.database.ports['27017'] }}/test?authSource=admin&replicaSet=rs0


