name: MongoDB Replica Set In Container In GitHub Actions

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build db image
        run: |
            docker build -t mongo-db .
        working-directory: .
      - name: Start the database
        run: |
            docker run \
                -d \
                --rm \
                -p 27017:27017 \
                mongo-db \
                --replSet "rs0" \
                mongod
        working-directory: .
      - name: Test the database
        run: |
            set -e

            mongo mongodb://admin:password@localhost:27017/test?authSource=admin&replicaSet=rs0

