name: MongoDB Replica Set In Container In GitHub Actions

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: mongo:4.0.12
        ports:
          - 27017/tcp
    steps:
      - uses: actions/checkout@v2
      - name: Start the database
        env:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: admin
        run: mongod --port ${{ job.services.database.ports['27017'] }} --replSet "rs0" --dbpath . --fork --syslog
      - name: Initialize the replica set
        env:
            MONGO_PORT: ${{ job.services.database.ports['27017'] }}
        run: |
            set -e

            mongo <<EOF
                rs.initiate({
                    _id : "rs0",
                    members: [
                        { _id: 0, host: "localhost:$MONGO_PORT" }
                    ]
                });

                while (rs.status().myState !== 1) {
                    print('sleeping...');
                    sleep(200);
                }

                exit
            EOF
      - name: Test the database
        run: |
            set -e

            mongo mongodb://admin:password@localhost:${{ job.services.database.ports['27017'] }}/test?authSource=admin&replicaSet=rs0

